### ISSUE TITLE
Export Captures to Screenshot Directory or User Specified Place

### ISSUE THREAD

**Issue by Turioyt** [chrrs/camerapture#7]
### What do you want added or changed?

An option to be able to save/ export a captured image to the users computer. It could be a ui element on one of the corners of the screen when you right click to view an image. Right now, at least in single player (which is what I mainly use it in), you do get the .webp files inside of the world file. However, I think it would be a bit of a hassle to have to move those files to somewhere else after each session. So I feel this feature would be pretty convenient.

**Comment by chrrs** [comment]
Yes! This is something I've been meaning to add. I think I want to do this by adding two buttons, either on right-click or just in the UI itself to copy and save the image. It would then save as a png, as webp files are a bit annoying to deal with, I'm only really using them because they're really efficient in size.

**Comment by chrrs** [comment]
Took a bit, but I've added a Ctrl-S keybinding when viewing the picture to save it to your disk! This should be in the next version that's released.
