### ISSUE TITLE
Compatibility issue with Replay Mod

### ISSUE THREAD

**Issue by whatamaniac** [chrrs/camerapture#9]
### What's the issue?

Hello, I'm trying to render a replay recording and the Images in the replay recording does not load and says "Fetching Picture ... ". Every picture says the same. I've attached a video please do have a look and lemme know if there's a way i can make this work by tweaking some file info or any other way to get this working.

### Screenshots

https://github.com/chrrs/camerapture/assets/75019293/7015d5da-0509-41b3-b53d-aa626b2dc43c

### Mod and Minecraft version

Camerapture-1.1.2+mc1.20.1

**Comment by chrrs** [comment]
Hmm that's a good one. The reason that doesn't work is because pictures are always fetched server-side, and not cached client-side, so when replaying a recording, there's no server to request the pictures from, and they will never be loaded.

I do have an idea on how to fix this! I'll see if I can somehow detect Replay mod recording, and if so, cache pictures client-side so they load.

Now that I'm thinking about it, maybe it wouldn't be a bad idea in general just to cache everything client-side anyways. In any case, I'll make sure it works in the near future!

---

Unfortunately there's not much you can do to make it work right now though, sorry.

**Comment by whatamaniac** [comment]
Ok No worries ^_^

**Comment by chrrs** [comment]
I've just released 1.2.0, and it should fix this!
